### ISSUE TITLE
Error executing a query in an Excel File

### ISSUE THREAD

**Issue by Jordi3Rs** [gsimardnet/PowerQueryNet#10]
Hi

I have been trying pqnet with the several options it provides. I have experienced some problems trying to execute a query hosted in an Excel file with the message "_CreateMashupConnectionInfo has failed._". I could execute a query in a pbix file with no problems but I couldn't for an Excel file. 

Even, I have created a simple Excel file named **test.xlsx** with Hello World M query inside and named as **Query1**. When I just tried to execute it with the following command line: 

` pqnet test.xlsx Query1`

I got the same error as with other Excel files. 

Can you provide some insights about it?

Thanks
Jordi

**Comment by gsimardnet** [comment]
Hi Jordi,

There was a bug with Excel file sources. I have just released a new version to fix that.

Please download [Version 1.1.2](https://github.com/gsimardnet/PowerQueryNet/releases/tag/v1.1.2)

**Comment by Jordi3Rs** [comment]
Hi Guillaume,

Good!. 
I have tested it and now is working correctly. 

Many Thanks!
Jordi

**Comment by amks1** [comment]
@gsimardnet 
I'm getting this problem with the latest version still. Query is running perfectly in excel.

**Comment by gsimardnet** [comment]
If some files work but some others don't, I would assume that there is something unsupported in the formulas that failed.
