### ISSUE TITLE
Credential for Google Sheet URL not working

### ISSUE THREAD

**Issue by amks1** [gsimardnet/PowerQueryNet#15]
Hi @gsimardnet, thanks for building this wonderful tool.

I'm facing some trouble with setting the credentials file. I have a query in an excel file that pulls data from a google sheet that's published on the web. I'm trying to run pqnet on command line, and what I get is
`Credentials are required to connect to the Web source. (Source: from https://docs.google.com/spreadsheets/d/e/{my_url}/pub to https://doc-14-ac-sheets.googleusercontent.com/pub/l5l039s6ni5uumqbsj9o11lmdc/qp624dp2l1ak84fqggq0ki1pj8/1611085670000/112456903451302169848/*/e@.)`

I've tried to add these urls in the credentials xml, but it doesn't work. Is there a way I can connect to Google Sheets?

Thanks a lot!

**Comment by gsimardnet** [comment]
This question was answered in issue #13
