### ISSUE TITLE
Error: Query name must be defined

### ISSUE THREAD

**Issue by alazyworkaholic** [gsimardnet/PowerQueryNet#23]
I just installed pqnet, saved ```let Source = Text.Proper("Hello, World") in Source``` as "helloworld.pq" and ran ```pqnet helloworld.pq``` and received ```Query name must be defined```.

The error message is clear enough, but how do I define a query name? What step did I miss?

**Comment by alazyworkaholic** [comment]
Found out: run ```pqnet``` without any arguments to see the syntax is ```pqnet source [query name] [options]```
Apparently, query name is actually a required argument.

**Comment by gsimardnet** [comment]
I am not sure why Query Name is required in your test. I tried the same thing and was able to output the result by running `pqnet helloworld.pq`
