### ISSUE TITLE
Error when call Execute

### ISSUE THREAD

**Issue by andreyminakov** [gsimardnet/PowerQueryNet#4]
When I launch any project from this repo, even PowerQueryHelloWorld, I get error 
"No endpoint listening for net.pipe://localhost/PowerQueryNet/". 

What may be the problem?

I just downloaded the repo, opened PowerQueryNet.Samples.sln and launched Helloworld.

**Comment by gsimardnet** [comment]
Hi,

The samples (or any project that references the PowerQueryNet.Client) are calling the PowerQueryNet Service in background. It's a Windows service that must be installed on your machine. To install the service you can either :
  1- Download [PowerQueryNet.msi](../releases/download/v1.0.3/PowerQueryNet.msi) from the Release page
  2- Or compile the Setup project to regenerate PowerQueryNet.msi

Then you only need to install this msi to have the service installed on your machine. Please note that this msi depends on [PowerQuerySdk.vsix 1.0.0.16](http://dakahn.gallery.vsassets.io/_apis/public/gallery/publisher/dakahn/extension/powerquerysdk/1.0.0.16/assetbyname/PowerQuerySdk.vsix). This file contains all the binaries of Power Query developped by Microsoft and it must be in the same directory of the msi when you install this service.

Thank you for your interest in this project.
