### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by Jordi3Rs** [gsimardnet/PowerQueryNet#5]
Hi, 
I am just wondering if there is an update coming compatible with newer SDK version such as 10.0.0.20. I was trying to install the last version of PowerQueryNet with last SDK version (i.e.10.0.0.20) and it didn't work. Finally, I tried it with controlled SDK version (i.e. 10.0.0.16) and it worked fine.
Is there any chance that PowerQueryNet would be mainly independent of the SDK version?

Thanks in advance and congratulations for the project. 
Jordi

**Comment by gsimardnet** [comment]
Hi,
For now, I keep compatibility to version 1.0.0.16 because it is the last version to run at 64-bit.
If you notice that you are missing a new feature, please let me know.
Thank you for your interest in the project.

**Comment by Jordi3Rs** [comment]
Thanks for the response Guillaume,

I didn't know the latest versions of the SDK were not 64 bits. In fact, I couldn't see it in the visual studio market place (https://marketplace.visualstudio.com/items?itemName=Dakahn.PowerQuerySDK). In any case, as you are suggesting, probably the main functionalities should work with 10.0.0.16 version. I just noticed it is not the last version, and the last one seems to be stable for almost 1 year ago. 

Anyway, if I observe any issue I will post it over here. 

Thanks
Jordi
