### ISSUE TITLE
Credentials not working for folder

### ISSUE THREAD

**Issue by ghoshsujoy19** [gsimardnet/PowerQueryNet#6]
Hi, I was trying this tool but when it came to give credentials to folder, it failed with the following message..
![image](https://user-images.githubusercontent.com/26358179/58690741-e36f2580-83a7-11e9-8c19-860c3ca05cdf.png)

here is my code :
![image](https://user-images.githubusercontent.com/26358179/58690893-3ba62780-83a8-11e9-8685-18415e3fdbab.png)

Here is the Mashup Script:
![image](https://user-images.githubusercontent.com/26358179/58691041-8cb61b80-83a8-11e9-9133-ec6b665574ee.png)

What should I do about it?? Or, do you know how to make Credentials from an XML file... means the format of the XML document..?

**Comment by gsimardnet** [comment]
Hi,

Power Query see Folder distinctly from File so we must provide a new "CredentialFolder" class.
Thanks for raising that issue. I will add this option in the upcoming release.

Regards,

**Comment by gsimardnet** [comment]
I have added support for "CredentialFolder" in [v1.1.0](https://github.com/gsimardnet/PowerQueryNet/releases/tag/v1.1.0)
