### ISSUE TITLE
Documentation on credentials format?

### ISSUE THREAD

**Issue by hiptopjones** [gsimardnet/PowerQueryNet#8]
When trying to load a CSV file in a .pq file via pqnet.exe, I get the following:

> Credentials are required to connect to the File source.

I notice that pqnet has a credentials parameter, and in the samples download I see a credentials file that looks like this:

`<Credentials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Credential xsi:type="CredentialSQL">
    <SQL>.\sql2016;AdventureWorks2012</SQL>
  </Credential>
  <Credential xsi:type="CredentialFile">
    <Path>Z:\TMP\eConnect\Archive\PM_Simplex_201702061100.xml</Path>
  </Credential>
  <Credential xsi:type="CredentialFile">
    <Path>Z:\Desktop\PowerQueryApp\MyExcel\List1.xls</Path>
  </Credential>
</Credentials>`

Where can I find documentation on the credential format?  What are the credentials that are needed for accessing a CSV file?  Will I need a separate credential for each CSV file I'm accessing?

I didn't see any other issues around this, so maybe I am missing something obvious.

Thanks in advance.

**Comment by gsimardnet** [comment]
Hi,

To access you CSV file, you can create a specific credential of type CredentialFile like you see in the sample. You can also have a single CredentialFolder to access every files in that folder. 

For instance, to access C:\MyFolder, the content of your credentials file would be :
`<Credentials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<Credential xsi:type="CredentialFolder">
		<Path>C:\MyFolder</Path>
	</Credential>
</Credentials>`

Then you would need to use the -c argument to reference your credentials file :
`pqnet myquery.pq -c mycredentials.xml`

**Comment by hiptopjones** [comment]
Great, thanks!  That works.
